name:                LunchLine

default-extensions:
- OverloadedStrings
- DerivingStrategies
- GeneralizedNewtypeDeriving

dependencies:
- base >= 4.7 && < 5
- persistent
- persistent-sqlite
- mtl
- resource-pool
- monad-logger
- esqueleto

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  LunchLine-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LunchLine

tests:
  LunchLine-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LunchLine
